### ISSUE TITLE
Sonic Jump 1 (Brazil, Siemens 132x176) off-by-one issue in the menu and music issue

### ISSUE THREAD

**Issue by TwoSpacesSG** [TASEmulators/freej2me-plus#16]
First off the music issue out of the way: the title music does not loop, and starting a stage also starts up the title music for 1 loop even though it shouldn't. This is what i originally wanted to report but then i noticed the menu issue. I think music is off by default in this game or something, but you can turn it on in the options menu.

Menu issue: The right softkey (siemens) does not work. Center key works as intended, but left softkey, for some reason, selects the option one slot above the option that is highlighted. If you're highlighting "play" (translated into English), then it will select "quit game" because going up one will highlight that option. If you have Green Hill and Blue Sky unlocked, then pressing left softkey on Green Hill will start you in Blue Sky, and so on.

**Comment by AShiningRay** [comment]
Huh... the 240x320 version i have (nokia 6280 i think) works perfectly fine, audio included. Couldn't find any siemens specific jar either, most of what i've come around at this resolution range is for lower-end S40 variants.

In any case, i guess a rework on the compatibility list would be helpful, since many games have jars that work perfectly fine, and others that don't even get past the main menu. (but then there's also the dubious jar dumps that do not work even on actual j2me hardware... oh well)

**Comment by TwoSpacesSG** [comment]
It appears that the only remaining issue in Sonic Jump 1 is the non-looping title music.
